import { REF_RATIO } from '../constants/platform';

const PureWhite = '#FFF';
const DarkWhite = '#9FB2BC';
const ElectricViolet = '#8A07ED';
const RedCrayola = '#FF0054';
const OrangePantone = '#ff5400';
const Mango = '#FFBD00';
const Black = '#000';

export default {
  PRIMARY_COLOR: ElectricViolet,
  SECONDARY_COLOR: RedCrayola,
  BACKGROUND_COLOR: PureWhite,
  FONT_SIZE_XSMALL: 11 * REF_RATIO,
  FONT_SIZE_SMALL: 12 * REF_RATIO,
  FONT_SIZE_MEDIUM: 14 * REF_RATIO,
  FONT_SIZE_LARGE: 16 * REF_RATIO,
  FONT_SIZE_XLARGE: 18 * REF_RATIO,
  FONT_LINE_XSMALL: 13 * REF_RATIO,
  FONT_LINE_SMALL: 14 * REF_RATIO,
  FONT_LINE_MEDIUM: 16 * REF_RATIO,
  FONT_LINE_LARGE: 19 * REF_RATIO,
  FONT_LINE_XLARGE: 21 * REF_RATIO,
  TEXT_LIGHT: PureWhite,
  TEXT_DARK: Black,
  TAB_BAR_HEIGHT_SMALL: 30 * REF_RATIO,
  TAB_BAR_HEIGHT_MEDIUM: 40 * REF_RATIO,
  TAB_BAR_HEIGHT_LARGE: 50 * REF_RATIO,
  MARGIN_SMALL: 10 * REF_RATIO,
  MARGIN_MEDIUM: 20 * REF_RATIO,
  MARGIN_LARGE: 30 * REF_RATIO,
  BORDER_RADIUS: 5 * REF_RATIO,
  INPUT_HEIGHT_SMALL: 40 * REF_RATIO,
  INPUT_HEIGHT_MEDIUM: 50 * REF_RATIO,
  BUTTON_HEIGHT: 60 * REF_RATIO,
  CELL_HEIGHT_SMALL: 40 * REF_RATIO,
  CELL_HEIGHT_MEDIUM: 60 * REF_RATIO,
};
